databases:
  - name: logistics-db
    databaseName: logistics_db
    user: logistics_user

services:
  - type: web
    name: logistics-api
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn logistics_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: logistics-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False