databases:
  - name: logistics-db
    databaseName: logistics_db
    user: logistics_user

services:
  - type: web
    name: logistics-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn logistics_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: logistics-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.13.9